---
- hosts: web_server
  become: true
  tasks:
    - name: Ping the server
      ansible.builtin.ping:
      register: ping_result

    - name: Print ping result
      ansible.builtin.debug:
        msg: "{{ 'pong' if ping_result is success else 'Failed to ping' }}"
